# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Midterm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Midterm
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'

end
